### ISSUE TITLE
Compile Errror

### ISSUE THREAD

**Issue by merlano17** [evolute-pt/dbtransfer#12]
Am trying to compile the project and following the steps as mentioned here https://travis-ci.org/evolute-pt/dbtransfer

I get so many errors it doesnt get compiled correctly
[ERROR] /var/www/evolute-pt/dbtransfer/src/main/java/pt/evolute/dbtransfer/transfer/AsyncStatement.java:[21,29] generics are not supported in -source 1.3

This issue is fixed once i installed maven2, before i only installed maven

Thanks

**Comment by mgarces** [comment]
Thank you for your feedback, and sorry for the long time to reply... I have been away and didn't get any notification for this. We will look into this error, so other like you don't get this again! Thank you!
